### PR TITLE
Create [WIP]2016-09-09-september-2016-azure-iot-using-node.md

### PR DESCRIPTION
**Pull request by hamoore**
@ryan-roemer ready for review :)

### CODE REVIEW

**Comment by hamoore** [comment]
@ryan-roemer title fixed!

**Comment by ryan-roemer** [comment]
@hamoore -- LGTM! We can merge once meetup live event is posted and we have the meetup link!

**Comment by hamoore** [comment]
@ryan-roemer Meetup live and updated! :shipit:?

**Comment by ryan-roemer** [comment]
LGTM!

**Pull request merged**
